/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mazgi_android_sqlite3driver4androidsdk_JNIBridge */

#ifndef _Included_com_mazgi_android_sqlite3driver4androidsdk_JNIBridge
#define _Included_com_mazgi_android_sqlite3driver4androidsdk_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mazgi_android_sqlite3driver4androidsdk_JNIBridge
 * Method:    doNothing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mazgi_android_sqlite3driver4androidsdk_JNIBridge_doNothing
  (JNIEnv *, jobject);

/*
 * Class:     com_mazgi_android_sqlite3driver4androidsdk_JNIBridge
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mazgi_android_sqlite3driver4androidsdk_JNIBridge_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mazgi_android_sqlite3driver4androidsdk_JNIBridge
 * Method:    callSQLite3Driver
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mazgi_android_sqlite3driver4androidsdk_JNIBridge_callSQLite3Driver
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
